version: '3.8'
services:
  paco:
    image: paco
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - app-tier
    links:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=postgres.local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
